#!/usr/bin/env python3
"""Generate a 128-byte EDID advertising exactly the modes the qualification scenarios
need, so a GNOME or Plasma guest's virtio-gpu connector offers all of them.

QEMU's virtio-gpu offers either a 4K-capable mode set (edid=on) or the DMT common set
with 720p (edid=off), never both, and the compositor's DisplayConfig accepts only
advertised modes -- so the desktop guests load this EDID over the connector with the
kernel's `drm.edid_firmware`. It carries three CVT-reduced-blanking detailed timings:
3840x2160 (the 4K scenario), 1920x1080 (the fixture default) and 1280x720 (resize).

    scripts/kvm/make-edid.py OUTPUT.bin

The blob is deterministic; it is regenerated by the guest builder and never committed.
"""

import struct
import sys

# (width, height, refresh). The guest's virtio-gpu connector always prunes the FIRST
# (preferred) detailed timing of a firmware EDID -- proven empirically on this lab's
# guests: an EDID whose first timing is 1080p yields no 1080p at all, one whose first
# timing is 4K yields no 4K, and so on; every timing after the first survives. So the
# first entry is a sacrificial throwaway the kernel drops, and the three timings the
# scenarios actually need (4K, 1080p, 720p) follow it and all reach the compositor.
# 4K is 30 Hz on purpose: its 60 Hz CVT clock (~533 MHz) is pruned as too fast, while
# ~266 MHz at 30 Hz is accepted, and refresh does not matter for a VNC capture.
MODES = [
    (1600, 1200, 60),  # sacrificial: the connector always drops the first timing
    (3840, 2160, 30),
    (1920, 1080, 60),
    (1280, 720, 60),
]


def cvt_reduced(width: int, height: int, refresh: int = 60) -> dict:
    """CVT reduced-blanking v1 timings for a mode, enough for an EDID detailed block."""
    h_blank = 160  # RB fixes horizontal blanking at 160 px
    v_sync = 8
    # RB vertical blanking is a fixed 460 us minimum expressed in lines.
    h_total = width + h_blank
    v_blank = max(
        v_sync + 6,
        round(460 * (refresh * (height + 1)) / 1_000_000) + 1,
    )
    v_total = height + v_blank
    pixel_clock_khz = round(h_total * v_total * refresh / 1000 / 10) * 10
    return {
        "width": width,
        "height": height,
        "pixel_clock": pixel_clock_khz,
        "h_blank": h_blank,
        "v_blank": v_blank,
        "h_front": 48,  # RB fixed
        "h_sync": 32,  # RB fixed
        "v_front": 3,  # RB fixed
        "v_sync": v_sync,
    }


def detailed_timing(mode: dict) -> bytes:
    """An 18-byte EDID detailed timing descriptor for a CVT mode."""
    clock = mode["pixel_clock"] // 10  # in 10 kHz units
    w, h = mode["width"], mode["height"]
    hb, vb = mode["h_blank"], mode["v_blank"]
    hfp, hsw = mode["h_front"], mode["h_sync"]
    vfp, vsw = mode["v_front"], mode["v_sync"]
    return bytes(
        [
            clock & 0xFF,
            (clock >> 8) & 0xFF,
            w & 0xFF,
            hb & 0xFF,
            ((w >> 8) << 4) | (hb >> 8),
            h & 0xFF,
            vb & 0xFF,
            ((h >> 8) << 4) | (vb >> 8),
            hfp & 0xFF,
            hsw & 0xFF,
            ((vfp & 0xF) << 4) | (vsw & 0xF),
            ((hfp >> 8) << 6) | ((hsw >> 8) << 4) | ((vfp >> 4) << 2) | (vsw >> 4),
            0,  # image size and border: unused
            0,
            0,
            0,
            0,
            0b00011110,  # digital separate sync, +h +v
        ]
    )


def descriptor_text(tag: int, text: str) -> bytes:
    """An 18-byte EDID descriptor carrying a short ASCII string (name or serial)."""
    body = text.encode("ascii")[:13].ljust(13, b"\x0a" if len(text) < 13 else b" ")
    return bytes([0, 0, 0, tag, 0]) + body


def main() -> None:
    out = sys.argv[1]
    edid = bytearray(128)
    edid[0:8] = bytes([0x00, 0xFF, 0xFF, 0xFF, 0xFF, 0xFF, 0xFF, 0x00])
    # Manufacturer "WVN" (5-bit letters), product 0x01, serial, week/year.
    letters = (ord("W") - 64, ord("V") - 64, ord("N") - 64)
    mfg = (letters[0] << 10) | (letters[1] << 5) | letters[2]
    edid[8:10] = struct.pack(">H", mfg)
    edid[10:12] = struct.pack("<H", 0x0001)
    edid[12:16] = struct.pack("<I", 0x00000001)
    edid[16] = 0  # week
    edid[17] = 2026 - 1990  # year
    edid[18] = 1  # EDID 1.4
    edid[19] = 4
    # Digital input, 8 bpc, DisplayPort; 60x34 cm; standard sRGB gamma; features.
    edid[20] = 0b10100101
    edid[21] = 60
    edid[22] = 34
    edid[23] = 120
    edid[24] = 0b00000110
    edid[25:35] = bytes(10)  # chromaticity: left as zeros (unused by the mode list)
    edid[35:38] = bytes([0x00, 0x00, 0x00])  # no established timings
    for i in range(38, 54):  # no standard timings
        edid[i] = 0x01
    # The four 18-byte descriptor slots: the timings first (the first is the sacrificial
    # one above), then the monitor name if a slot is free, then unused-descriptor
    # padding. Four timings fill every slot, so the name is only present with fewer.
    blocks = [detailed_timing(cvt_reduced(w, h, r)) for w, h, r in MODES]
    if len(blocks) < 4:
        blocks.append(descriptor_text(0xFC, "wayland-vnc"))  # monitor name
    while len(blocks) < 4:
        blocks.append(bytes([0, 0, 0, 0x10, 0]) + bytes(13))  # unused descriptor
    descriptors = b"".join(blocks)
    assert len(descriptors) == 72, len(descriptors)
    edid[54:126] = descriptors
    edid[126] = 0  # no extension blocks
    edid[127] = (-sum(edid[:127])) & 0xFF  # checksum: bytes sum to 0 mod 256
    with open(out, "wb") as handle:
        handle.write(edid)


if __name__ == "__main__":
    main()
